data:
  data: GDSCv2
  dir: '/home/nas/lk/mol_generate/gdscv2_GDSS/'
  batch_size: 128
  max_node_num: 96
  max_feat_num: 10
  init: atom

# data:
#   data: GDSCv2_SMALL
#   dir: 'data/'
#   batch_size:    
#     train: 256
#     test: 256
#   max_node_num: 96
#   max_feat_num: 10
#   init: atom


sde:
  x: 
    type: VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000
  adj:
    type: VE
    beta_min: 0.2
    beta_max: 1.0
    num_scales: 1000

model:
  x: ScoreNetworkX
  adj: ScoreNetworkA
  conv: GCN
  num_heads: 4
  depth: 2
  adim: 16
  nhid: 16
  num_layers: 4
  num_linears: 3
  c_init: 4
  c_hid: 8
  c_final: 4

train:
  name: condition_rand_30%_mask
  num_epochs: 300
  save_interval: 5
  print_interval: 5
  reduce_mean: False
  lr: 0.0005
  lr_schedule: True
  ema: 0.999
  weight_decay: 0.0001
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 1.0e-5
