data:
  data: ZINC250k
  dir: '/home/lk/project/mol_generate/GDSS/data'
  batch_size: 
    train: 512
    test: 512
  # max_node_num: 38
  # max_feat_num: 9
  max_node_num: 100
  max_feat_num: 10
  init: atom

sde:
  x: 
    type: VP
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000
  adj:
    type: VE
    beta_min: 0.1
    beta_max: 1.0
    num_scales: 1000

model:
  x: ScoreNetworkX
  adj: ScoreNetworkA
  conv: GCN
  num_heads: 4
  depth: 2
  adim: 16
  nhid: 16
  num_layers: 3
  num_linears: 3
  c_init: 2
  c_hid: 8
  c_final: 4

train:
  name: zinc250k_maxAtom_100
  num_epochs: 500
  save_interval: 10
  print_interval: 10
  reduce_mean: False
  lr: 0.01
  lr_schedule: True
  ema: 0.999
  weight_decay: 0.0001
  grad_norm: 1.0
  lr_decay: 0.999
  eps: 1.0e-5
